package errors

var ErrorCodeMap = map[string]string{
	"USER_NOT_FOUND":        "User not found",
	"INVALID_CREDENTIAL":    "Invalid username or password",
	"DB_ERROR":              "Database error occurred",
	"INTERNAL_ERROR":        "Internal server error",
	"ROLE_NOT_FOUND":        "Role not found",
	"PERMISSION_DENIED":     "Permission denied",
	"INVALID_INPUT":         "Invalid input provided",
	"EMAIL_ALREADY_EXISTS":  "Email already exists",
	"PHONE_ALREADY_EXISTS":  "Phone number already exists",
	"UNAUTHORIZED":          "Unauthorized access",
	"RESOURCE_NOT_FOUND":    "Requested resource not found",
	"INVALID_TOKEN":         "Invalid or expired token",
	"PASSWORD_MISMATCH":     "Password does not match",
	"USER_ALREADY_EXISTS":   "User already exists",
	"ROLE_ALREADY_EXISTS":   "Role already exists",
	"EMAIL_NOT_VERIFIED":    "Email not verified",
	"PHONE_NOT_VERIFIED":    "Phone number not verified",
	"ACCOUNT_LOCKED":        "Account is locked",
	"TOO_MANY_REQUESTS":     "Too many requests, please try again later",
	"INVALID_FILE_TYPE":     "Invalid file type uploaded",
	"FILE_TOO_LARGE":        "Uploaded file is too large",
	"OPERATION_NOT_ALLOWED": "Operation not allowed",
	"RESOURCE_CONFLICT":     "Resource conflict occurred",
	"INVALID_REQUEST":       "Invalid request",
}
